### ISSUE TITLE
Creating a simple back-end.

### ISSUE THREAD

**Issue by syntaxbullet** [syntaxbullet/Kiara#1]
The aim of this task is to implement a simple Express.js based back-end service. The back-end will be utilizing Typescript and if possible avoid the usage of ORMs like Prisma.

### Requirements 📌

- The back-end should expose simple CRUD routes related to managing simple user information such as email password and profile picture.
- The back-end should allow for simple authentication by providing an email and a password.
- protected routes should only be accessible by signed-in users. 

### Design Guidelines 🎨

- The application should leverage the Hexagonal Architecture, allowing for a less coupled and more modular approach to the storage of data and management of state.
- Typescript is required, keep the types as strict as possible to help avoid future issues.
- The authentication should leverage JWT tokens in a completely stateless manner.
- Usage of ORMs should be avoided.

### Implementation Steps 🛠️

- [x] **Create a new Express project using Typescript**: Set up a new Express project using Typescript.
- [x]  **Figure out a suitable folder structure**: learn about applying the ports and adapters architecture in express.js projects.
- [x]  **Integrate JWT**: Install the `jsonwebtoken` package and research on how to best implement stateless authentication using it.
- [x] **Connect to DB**: Connect to a suitable database. SQLite or PG.
- [ ] **Write tests**: Make sure all of your functionality can be tested, verify the correct application of the Hexagonal architecture.

### Resources 🔗
- *ExpressJS Docs*: [Docs](http://expressjs.com/en/4x/api.html)
- *Typescript Docs*: [Docs](https://www.typescriptlang.org/docs/)
- *JWT Introduction*: [Guide](https://jwt.io/introduction/)
- *Reference Implementation*: [Reference](https://github.com/eldimious/nodejs-api-showcase)
